##### 遇到问题：递归次数大时，报堆栈溢出的错误。改写成尾递归形式，依然报错。

示例代码：

递归：

```js
const add = (n) => {
	if (n == 1) return 1;
	return n + add(n - 1);
}
console.log("result：",add(100000))
```

尾递归

```js
const add = (n, total = 0) => {
	if (n == 0) return total;
	return add(n - 1, total + n);
}
console.log("result：",add(100000))
```

如果js解释器有实现尾递归优化，分析两种递归代码的递归过程：假设n=5

普通递归：（递归过程）

add(5)

5+add(4)

5+(4+add(3))

5+(4+(3+add(2)))

5+(4+(3+(2+add(1)))

5+(4+(3+(2+1)))

5+(4+(3+3))

5+(4+6)

5+10

15

尾递归：（迭代过程）

add(5,0)

add(4,5)

add(3,9)

add(2,12)

add(1,14)

add(0,15)

15

报错原因：chrome的js解释器没有尾递归优化，随着程序的运行，函数的调用栈不断增加，超过解释器设置的栈顶，程序就会报错。

解决办法：改递归为循环（使用Trampoline，不直接调用自身，形成递归；而是返回一个参数就绪的函数，以备外部调用）

```js
const add = (n, total = 0) => {
	if (n < 1) return total;
	return add.bind(null, n - 1, total + n)

}

trampoline = (n) => {
	fn = add(n, 0);
	while (typeof fn == 'function') {
		fn = fn();
	}
	return fn;
}

console.log("result",trampoline(100000))
```

